spring:
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: false

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:dslearn}
      client-secret: ${CLIENT_SECRET:dslearn123}

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:86400}